//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace st1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/ST1_Backend")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PopularityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private st1.ServiceReference1.Review[] ReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private st1.ServiceReference1.ShoppingCart[] ShoppingCartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateAdded {
            get {
                return this.DateAddedField;
            }
            set {
                if ((this.DateAddedField.Equals(value) != true)) {
                    this.DateAddedField = value;
                    this.RaisePropertyChanged("DateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Popularity {
            get {
                return this.PopularityField;
            }
            set {
                if ((this.PopularityField.Equals(value) != true)) {
                    this.PopularityField = value;
                    this.RaisePropertyChanged("Popularity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public st1.ServiceReference1.Review[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public st1.ServiceReference1.ShoppingCart[] ShoppingCarts {
            get {
                return this.ShoppingCartsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingCartsField, value) != true)) {
                    this.ShoppingCartsField = value;
                    this.RaisePropertyChanged("ShoppingCarts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockQuantity {
            get {
                return this.StockQuantityField;
            }
            set {
                if ((this.StockQuantityField.Equals(value) != true)) {
                    this.StockQuantityField = value;
                    this.RaisePropertyChanged("StockQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/ST1_Backend")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private st1.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReviewDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReviewIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private st1.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public st1.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReviewDate {
            get {
                return this.ReviewDateField;
            }
            set {
                if ((this.ReviewDateField.Equals(value) != true)) {
                    this.ReviewDateField = value;
                    this.RaisePropertyChanged("ReviewDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReviewID {
            get {
                return this.ReviewIDField;
            }
            set {
                if ((this.ReviewIDField.Equals(value) != true)) {
                    this.ReviewIDField = value;
                    this.RaisePropertyChanged("ReviewID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReviewText {
            get {
                return this.ReviewTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewTextField, value) != true)) {
                    this.ReviewTextField = value;
                    this.RaisePropertyChanged("ReviewText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public st1.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCart", Namespace="http://schemas.datacontract.org/2004/07/ST1_Backend")]
    [System.SerializableAttribute()]
    public partial class ShoppingCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CartItemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private st1.ServiceReference1.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private st1.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CartItemID {
            get {
                return this.CartItemIDField;
            }
            set {
                if ((this.CartItemIDField.Equals(value) != true)) {
                    this.CartItemIDField = value;
                    this.RaisePropertyChanged("CartItemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public st1.ServiceReference1.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public st1.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ST1_Backend")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateRegisteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private st1.ServiceReference1.Invoice[] InvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private st1.ServiceReference1.Review[] ReviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private st1.ServiceReference1.ShoppingCart[] ShoppingCartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateRegistered {
            get {
                return this.DateRegisteredField;
            }
            set {
                if ((this.DateRegisteredField.Equals(value) != true)) {
                    this.DateRegisteredField = value;
                    this.RaisePropertyChanged("DateRegistered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public st1.ServiceReference1.Invoice[] Invoices {
            get {
                return this.InvoicesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicesField, value) != true)) {
                    this.InvoicesField = value;
                    this.RaisePropertyChanged("Invoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsManager {
            get {
                return this.IsManagerField;
            }
            set {
                if ((this.IsManagerField.Equals(value) != true)) {
                    this.IsManagerField = value;
                    this.RaisePropertyChanged("IsManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public st1.ServiceReference1.Review[] Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecName {
            get {
                return this.SecNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecNameField, value) != true)) {
                    this.SecNameField = value;
                    this.RaisePropertyChanged("SecName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public st1.ServiceReference1.ShoppingCart[] ShoppingCarts {
            get {
                return this.ShoppingCartsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingCartsField, value) != true)) {
                    this.ShoppingCartsField = value;
                    this.RaisePropertyChanged("ShoppingCarts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/ST1_Backend")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private st1.ServiceReference1.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceID {
            get {
                return this.InvoiceIDField;
            }
            set {
                if ((this.InvoiceIDField.Equals(value) != true)) {
                    this.InvoiceIDField = value;
                    this.RaisePropertyChanged("InvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((this.TotalAmountField.Equals(value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public st1.ServiceReference1.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReviewUser", Namespace="http://schemas.datacontract.org/2004/07/ST1_Backend")]
    [System.SerializableAttribute()]
    public partial class ReviewUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReviewDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReviewIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReviewDate {
            get {
                return this.ReviewDateField;
            }
            set {
                if ((this.ReviewDateField.Equals(value) != true)) {
                    this.ReviewDateField = value;
                    this.RaisePropertyChanged("ReviewDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReviewID {
            get {
                return this.ReviewIDField;
            }
            set {
                if ((this.ReviewIDField.Equals(value) != true)) {
                    this.ReviewIDField = value;
                    this.RaisePropertyChanged("ReviewID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReviewText {
            get {
                return this.ReviewTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewTextField, value) != true)) {
                    this.ReviewTextField = value;
                    this.RaisePropertyChanged("ReviewText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProducts", ReplyAction="http://tempuri.org/IService1/getProductsResponse")]
        st1.ServiceReference1.Product[] getProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProducts", ReplyAction="http://tempuri.org/IService1/getProductsResponse")]
        System.Threading.Tasks.Task<st1.ServiceReference1.Product[]> getProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductsByType", ReplyAction="http://tempuri.org/IService1/getProductsByTypeResponse")]
        st1.ServiceReference1.Product[] getProductsByType(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductsByType", ReplyAction="http://tempuri.org/IService1/getProductsByTypeResponse")]
        System.Threading.Tasks.Task<st1.ServiceReference1.Product[]> getProductsByTypeAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductById", ReplyAction="http://tempuri.org/IService1/getProductByIdResponse")]
        st1.ServiceReference1.Product getProductById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getProductById", ReplyAction="http://tempuri.org/IService1/getProductByIdResponse")]
        System.Threading.Tasks.Task<st1.ServiceReference1.Product> getProductByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editProduct", ReplyAction="http://tempuri.org/IService1/editProductResponse")]
        bool editProduct(st1.ServiceReference1.Product prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editProduct", ReplyAction="http://tempuri.org/IService1/editProductResponse")]
        System.Threading.Tasks.Task<bool> editProductAsync(st1.ServiceReference1.Product prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertNewProduct", ReplyAction="http://tempuri.org/IService1/InsertNewProductResponse")]
        bool InsertNewProduct(st1.ServiceReference1.Product prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertNewProduct", ReplyAction="http://tempuri.org/IService1/InsertNewProductResponse")]
        System.Threading.Tasks.Task<bool> InsertNewProductAsync(st1.ServiceReference1.Product prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteProduct", ReplyAction="http://tempuri.org/IService1/deleteProductResponse")]
        bool deleteProduct(int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteProduct", ReplyAction="http://tempuri.org/IService1/deleteProductResponse")]
        System.Threading.Tasks.Task<bool> deleteProductAsync(int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogIn", ReplyAction="http://tempuri.org/IService1/UserLogInResponse")]
        st1.ServiceReference1.User UserLogIn(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserLogIn", ReplyAction="http://tempuri.org/IService1/UserLogInResponse")]
        System.Threading.Tasks.Task<st1.ServiceReference1.User> UserLogInAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllUsers", ReplyAction="http://tempuri.org/IService1/getAllUsersResponse")]
        st1.ServiceReference1.User[] getAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllUsers", ReplyAction="http://tempuri.org/IService1/getAllUsersResponse")]
        System.Threading.Tasks.Task<st1.ServiceReference1.User[]> getAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        bool DeleteUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangeUserRole", ReplyAction="http://tempuri.org/IService1/ChangeUserRoleResponse")]
        bool ChangeUserRole(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ChangeUserRole", ReplyAction="http://tempuri.org/IService1/ChangeUserRoleResponse")]
        System.Threading.Tasks.Task<bool> ChangeUserRoleAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserInvoices", ReplyAction="http://tempuri.org/IService1/GetUserInvoicesResponse")]
        st1.ServiceReference1.Invoice[] GetUserInvoices(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserInvoices", ReplyAction="http://tempuri.org/IService1/GetUserInvoicesResponse")]
        System.Threading.Tasks.Task<st1.ServiceReference1.Invoice[]> GetUserInvoicesAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteInvoice", ReplyAction="http://tempuri.org/IService1/DeleteInvoiceResponse")]
        bool DeleteInvoice(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteInvoice", ReplyAction="http://tempuri.org/IService1/DeleteInvoiceResponse")]
        System.Threading.Tasks.Task<bool> DeleteInvoiceAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceById", ReplyAction="http://tempuri.org/IService1/GetInvoiceByIdResponse")]
        st1.ServiceReference1.Invoice GetInvoiceById(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceById", ReplyAction="http://tempuri.org/IService1/GetInvoiceByIdResponse")]
        System.Threading.Tasks.Task<st1.ServiceReference1.Invoice> GetInvoiceByIdAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registerUser", ReplyAction="http://tempuri.org/IService1/registerUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(st1.ServiceReference1.Product[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(st1.ServiceReference1.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(st1.ServiceReference1.Review[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(st1.ServiceReference1.Review))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(st1.ServiceReference1.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(st1.ServiceReference1.Invoice[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(st1.ServiceReference1.Invoice))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(st1.ServiceReference1.ShoppingCart[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(st1.ServiceReference1.ShoppingCart))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(st1.ServiceReference1.User[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(st1.ServiceReference1.ReviewUser[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(st1.ServiceReference1.ReviewUser))]
        object registerUser(string name, string secName, string surname, string passHash, string email, string address, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registerUser", ReplyAction="http://tempuri.org/IService1/registerUserResponse")]
        System.Threading.Tasks.Task<object> registerUserAsync(string name, string secName, string surname, string passHash, string email, string address, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getReviews", ReplyAction="http://tempuri.org/IService1/getReviewsResponse")]
        st1.ServiceReference1.ReviewUser[] getReviews(int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getReviews", ReplyAction="http://tempuri.org/IService1/getReviewsResponse")]
        System.Threading.Tasks.Task<st1.ServiceReference1.ReviewUser[]> getReviewsAsync(int prodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addReviews", ReplyAction="http://tempuri.org/IService1/addReviewsResponse")]
        bool addReviews(int prodId, int userId, int stars, string reviewText, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addReviews", ReplyAction="http://tempuri.org/IService1/addReviewsResponse")]
        System.Threading.Tasks.Task<bool> addReviewsAsync(int prodId, int userId, int stars, string reviewText, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateQuntity", ReplyAction="http://tempuri.org/IService1/updateQuntityResponse")]
        bool updateQuntity(int PId, int Qunt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateQuntity", ReplyAction="http://tempuri.org/IService1/updateQuntityResponse")]
        System.Threading.Tasks.Task<bool> updateQuntityAsync(int PId, int Qunt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCartQuntityfrom", ReplyAction="http://tempuri.org/IService1/getCartQuntityfromResponse")]
        int getCartQuntityfrom(int PId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCartQuntityfrom", ReplyAction="http://tempuri.org/IService1/getCartQuntityfromResponse")]
        System.Threading.Tasks.Task<int> getCartQuntityfromAsync(int PId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addProdToCart", ReplyAction="http://tempuri.org/IService1/addProdToCartResponse")]
        bool addProdToCart(int prodId, int userId, int quntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addProdToCart", ReplyAction="http://tempuri.org/IService1/addProdToCartResponse")]
        System.Threading.Tasks.Task<bool> addProdToCartAsync(int prodId, int userId, int quntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromCart", ReplyAction="http://tempuri.org/IService1/removeFromCartResponse")]
        bool removeFromCart(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromCart", ReplyAction="http://tempuri.org/IService1/removeFromCartResponse")]
        System.Threading.Tasks.Task<bool> removeFromCartAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCartProducts", ReplyAction="http://tempuri.org/IService1/getCartProductsResponse")]
        st1.ServiceReference1.Product[] getCartProducts(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCartProducts", ReplyAction="http://tempuri.org/IService1/getCartProductsResponse")]
        System.Threading.Tasks.Task<st1.ServiceReference1.Product[]> getCartProductsAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : st1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<st1.ServiceReference1.IService1>, st1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public st1.ServiceReference1.Product[] getProducts() {
            return base.Channel.getProducts();
        }
        
        public System.Threading.Tasks.Task<st1.ServiceReference1.Product[]> getProductsAsync() {
            return base.Channel.getProductsAsync();
        }
        
        public st1.ServiceReference1.Product[] getProductsByType(string type) {
            return base.Channel.getProductsByType(type);
        }
        
        public System.Threading.Tasks.Task<st1.ServiceReference1.Product[]> getProductsByTypeAsync(string type) {
            return base.Channel.getProductsByTypeAsync(type);
        }
        
        public st1.ServiceReference1.Product getProductById(int Id) {
            return base.Channel.getProductById(Id);
        }
        
        public System.Threading.Tasks.Task<st1.ServiceReference1.Product> getProductByIdAsync(int Id) {
            return base.Channel.getProductByIdAsync(Id);
        }
        
        public bool editProduct(st1.ServiceReference1.Product prod) {
            return base.Channel.editProduct(prod);
        }
        
        public System.Threading.Tasks.Task<bool> editProductAsync(st1.ServiceReference1.Product prod) {
            return base.Channel.editProductAsync(prod);
        }
        
        public bool InsertNewProduct(st1.ServiceReference1.Product prod) {
            return base.Channel.InsertNewProduct(prod);
        }
        
        public System.Threading.Tasks.Task<bool> InsertNewProductAsync(st1.ServiceReference1.Product prod) {
            return base.Channel.InsertNewProductAsync(prod);
        }
        
        public bool deleteProduct(int prodId) {
            return base.Channel.deleteProduct(prodId);
        }
        
        public System.Threading.Tasks.Task<bool> deleteProductAsync(int prodId) {
            return base.Channel.deleteProductAsync(prodId);
        }
        
        public st1.ServiceReference1.User UserLogIn(string email, string password) {
            return base.Channel.UserLogIn(email, password);
        }
        
        public System.Threading.Tasks.Task<st1.ServiceReference1.User> UserLogInAsync(string email, string password) {
            return base.Channel.UserLogInAsync(email, password);
        }
        
        public st1.ServiceReference1.User[] getAllUsers() {
            return base.Channel.getAllUsers();
        }
        
        public System.Threading.Tasks.Task<st1.ServiceReference1.User[]> getAllUsersAsync() {
            return base.Channel.getAllUsersAsync();
        }
        
        public bool DeleteUser(int userId) {
            return base.Channel.DeleteUser(userId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(int userId) {
            return base.Channel.DeleteUserAsync(userId);
        }
        
        public bool ChangeUserRole(int userId) {
            return base.Channel.ChangeUserRole(userId);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeUserRoleAsync(int userId) {
            return base.Channel.ChangeUserRoleAsync(userId);
        }
        
        public st1.ServiceReference1.Invoice[] GetUserInvoices(int userId) {
            return base.Channel.GetUserInvoices(userId);
        }
        
        public System.Threading.Tasks.Task<st1.ServiceReference1.Invoice[]> GetUserInvoicesAsync(int userId) {
            return base.Channel.GetUserInvoicesAsync(userId);
        }
        
        public bool DeleteInvoice(int invoiceId) {
            return base.Channel.DeleteInvoice(invoiceId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteInvoiceAsync(int invoiceId) {
            return base.Channel.DeleteInvoiceAsync(invoiceId);
        }
        
        public st1.ServiceReference1.Invoice GetInvoiceById(int invoiceId) {
            return base.Channel.GetInvoiceById(invoiceId);
        }
        
        public System.Threading.Tasks.Task<st1.ServiceReference1.Invoice> GetInvoiceByIdAsync(int invoiceId) {
            return base.Channel.GetInvoiceByIdAsync(invoiceId);
        }
        
        public object registerUser(string name, string secName, string surname, string passHash, string email, string address, string phone) {
            return base.Channel.registerUser(name, secName, surname, passHash, email, address, phone);
        }
        
        public System.Threading.Tasks.Task<object> registerUserAsync(string name, string secName, string surname, string passHash, string email, string address, string phone) {
            return base.Channel.registerUserAsync(name, secName, surname, passHash, email, address, phone);
        }
        
        public st1.ServiceReference1.ReviewUser[] getReviews(int prodId) {
            return base.Channel.getReviews(prodId);
        }
        
        public System.Threading.Tasks.Task<st1.ServiceReference1.ReviewUser[]> getReviewsAsync(int prodId) {
            return base.Channel.getReviewsAsync(prodId);
        }
        
        public bool addReviews(int prodId, int userId, int stars, string reviewText, System.DateTime date) {
            return base.Channel.addReviews(prodId, userId, stars, reviewText, date);
        }
        
        public System.Threading.Tasks.Task<bool> addReviewsAsync(int prodId, int userId, int stars, string reviewText, System.DateTime date) {
            return base.Channel.addReviewsAsync(prodId, userId, stars, reviewText, date);
        }
        
        public bool updateQuntity(int PId, int Qunt) {
            return base.Channel.updateQuntity(PId, Qunt);
        }
        
        public System.Threading.Tasks.Task<bool> updateQuntityAsync(int PId, int Qunt) {
            return base.Channel.updateQuntityAsync(PId, Qunt);
        }
        
        public int getCartQuntityfrom(int PId) {
            return base.Channel.getCartQuntityfrom(PId);
        }
        
        public System.Threading.Tasks.Task<int> getCartQuntityfromAsync(int PId) {
            return base.Channel.getCartQuntityfromAsync(PId);
        }
        
        public bool addProdToCart(int prodId, int userId, int quntity) {
            return base.Channel.addProdToCart(prodId, userId, quntity);
        }
        
        public System.Threading.Tasks.Task<bool> addProdToCartAsync(int prodId, int userId, int quntity) {
            return base.Channel.addProdToCartAsync(prodId, userId, quntity);
        }
        
        public bool removeFromCart(int Id) {
            return base.Channel.removeFromCart(Id);
        }
        
        public System.Threading.Tasks.Task<bool> removeFromCartAsync(int Id) {
            return base.Channel.removeFromCartAsync(Id);
        }
        
        public st1.ServiceReference1.Product[] getCartProducts(int userId) {
            return base.Channel.getCartProducts(userId);
        }
        
        public System.Threading.Tasks.Task<st1.ServiceReference1.Product[]> getCartProductsAsync(int userId) {
            return base.Channel.getCartProductsAsync(userId);
        }
    }
}
